server:
  port: 8080
  # ?? ?? ?? ??
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

#?????? ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pinshot
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

